services:
  # app:
  #   build: .
  #   container_name: snowflake_demo_app
  #   env_file: .env
  #   ports:
  #     - "8080:8080"
  #   depends_on: []
  localstack:
    container_name: "localstack-snowflake"
    image: localstack/snowflake
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:443:443"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
    volumes:
      - "./volume:/var/lib/localstack"